version: '2.1'
services:
  discovery:
    image: localhost:5000/discovery:latest
    restart: always

    ports:
     - "8761:8761"

  auth:
    image: localhost:5000/auth:latest
    restart: always
    depends_on:
     discovery:
        condition: service_healthy
    ports:
     - "8760:8760"

  gateway:
    image: localhost:5000/gateway:latest
    restart: always
    depends_on:
         discovery:
            condition: service_healthy

    links:
        - discovery
    ports:
     - "8765:8765"
  dividers-product:
    image: localhost:5000/dividers-product-service:latest
    restart: always
    depends_on:
         discovery:
            condition: service_healthy
    links:
        - discovery
    ports:
     - "1111:1111"
  dividers:
    image: localhost:5000/dividers-service:latest
    restart: always
    depends_on:
         discovery:
            condition: service_healthy
    links:
        - discovery
    ports:
     - "1112:1112"