version: '3.5'
services:
  discovery:
    build: ./support/discovery
    image: localhost:5000/discovery:latest
    restart: always

    ports:
     - "8761:8761"

  auth:
    image: localhost:5000/auth:latest
    restart: always
#    depends_on:
#     discovery:
#        condition: service_healthy
    ports:
     - "8760:8760"

  gateway:
    build: ./support/gateway
    image: localhost:5000/gateway:latest
    restart: always
#    depends_on:
#         -discovery:
#            condition: service_healthy

    links:
        - discovery
    ports:
     - "8765:8765"
  dividers-product:
    build: ./core/dividers-product-service
    image: localhost:5000/dividers-product-service:latest
    restart: always
#    depends_on:
#         discovery:
#            condition: service_healthy
    links:
        - discovery
    ports:
     - "1111:1111"
  dividers:
    build: ./core/dividers-service
    image: localhost:5000/dividers-service:latest
    restart: always
#    depends_on:
#         discovery:
#            condition: service_healthy
    links:
        - discovery
    ports:
     - "1112:1112"