info:
    component: Zuul Server

endpoints:
    restart:
        enabled: true
    shutdown:
        enabled: true
    health:
        sensitive: false

zuul:
    routes:
        dividers:
            path: /dividers/**
            serviceId: dividers-service
        dividers-product:
            path: /dividers-product/**
            serviceId: dividers-product-service

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10

server:
    port: 8765

logging:
    level:
        ROOT: INFO
        org.springframework.web: INFO
